import React from "react";

export default function Rules() {
  React.useEffect(() => {
    window.scrollTo(0, 0);
  }, []);
  return (
    <section>
      <div className="bg-primary-light  p-10 mb-10">
        <div className="max-w-2xl mx-auto text-center font-semibold text-[#FFFFFF]">
          <h3>
            Topper’s Pizza “Design Our Next Recipe Pizza” Contest (the
            “Contest”) <br /> 2023 Rules & Regulations
          </h3>
        </div>
      </div>

      <div className=" max-w-4xl mx-auto mb-10 px-6 md:px-0">
        <p>
          THIS CONTEST IS OPEN ONLY TO RESIDENTS OF ONTARIO AND IS GOVERNED BY
          CANADIAN LAW AND THE LAWS OF THE PROVINCE OF ONTARIO. SEE BELOW FOR
          FULL CONTEST DETAILS. PARTICIPATION IN THIS CONTEST CONSTITUTES FULL
          AND UNCONDITIONAL ACCEPTANCE OF, AND AGREEMENT TO BE LEGALLY BOUND BY,
          THESE CONTEST RULES (THE “<strong>OFFICIAL RULES</strong>”).
        </p>
        <br />
        <p className="style-p ">
          {" "}
          By entering this Contest, Entrants agree to abide by these Official
          Rules. The decisions of Topper’s Franchising Company Inc. (“
          <strong>Topper’s</strong>”) with respect to all aspects of the
          Contest, are final.{" "}
        </p>
        <br />
        <p>
          <strong>1. CONTEST PERIOD:</strong> The Contest begins at 09:00 am
          Eastern Standard Time (“ <strong>EST</strong>”) on April 3, 2023 and
          ends at 11:59 pm EST on June 25, 2023 (the “{" "}
          <strong>Contest Period</strong>”).
        </p>
        <br />
        <p>
          <strong>2. ELIGIBILITY:</strong> To enter and be eligible to win, a
          person must be a legal resident of Ontario who is age of majority or
          older at time of entry (an “<strong>Entrant</strong>”). Employees of
          Topper’s, its affiliates, subsidiaries, related companies, contest
          administrator, and advertising and promotional agencies (collectively
          the “<strong>Contest Parties</strong>”) and the immediate family
          (defined as mother, father, brothers, sisters, sons, daughters and/or
          legal or common-law spouse) of the Contest Parties and all other
          persons whom reside with the Contest Parties, are not eligible to
          enter the Contest.
        </p>
        <br />

        <strong>3. HOW TO ENTER THE CONTEST: No Purchase Necessary.</strong>
        <p>
          (a) Entries must be submitted by visiting topperscontest.ca and
          following the menus and data fields to submit all information related
          to the entry (the “<strong>Entry</strong>”).
        </p>
        <br />
        <p>
          (b) Entries must be received on or before 11:59 pm EST on June 25,
          2023 (the “<strong>Contest Closing Date</strong>”). Limit of one (1)
          Entry per person, per email address during the Contest Period. Only
          one (1) email address per person may be used. Anyone found to use
          multiple email addresses to enter will be ineligible. Proof of
          transmission (screenshots or captures, etc.) does not constitute proof
          of delivery. Entries generated by script, macro, robotic, programmed,
          or any other automated means are prohibited and will be disqualified.
        </p>
        <br />
        <p>
          <strong>4. PRIZE & APPROXIMATE RETAIL VALUE:</strong> There is one (1)
          grand prize (the “<strong>Prize</strong>”) of pizza for a year
          (consisting of 26 medium 3 topping pizzas) and valued at $107.90.
          Additionally, the winner’s pizza will also be included in a future
          Topper’s 2023/2024 campaign and marketed as a limited time offering.
          The winner’s pizza and their story (as deemed appropriate by Topper’s
          Marketing) will appear in various printed and digital materials
          throughout the campaign period.
          <br /> <br />
          Topper’s reserves the right to extend the winning pizza beyond the
          initial campaign period and add it as a permanent pizza offering on
          their menu. The winner is not entitled to any financial compensation
          from any future sales associated with their winning pizza.
          <br /> <br />
          The Prize must be accepted as awarded without substitution and cannot
          be transferred, assigned or redeemed for cash. In the event the Prize
          (or any component thereof) cannot be awarded for any reason, Topper’s
          reserves the right, in its sole discretion, to substitute another
          prize (or any component thereof) of equal or greater value, without
          liability. Any unused portion of the Prize will be forfeited and shall
          have no cash value. All characteristics and features of the Prize,
          except as otherwise explicitly stated above, will be determined by
          Topper’s in its sole and absolute discretion. Only one (1) Prize will
          be awarded.
        </p>
        <br />
        <p>
          <strong>5. WINNER SELECTION:</strong> One week following the June 25th
          Contest Closing Date deadline, a shortlist of five (5) contenders will
          be selected by the Topper’s Contest Team and contacted via email
          and/or telephone. If a selected Entrant (a) cannot be reached by email
          and/or telephone within three (3) business days of being contacted; or
          b) fails to return the properly executed Release Form within the
          specified time (see rule 6), then he/she will be disqualified and
          another Entrant will be contacted until such time as five (5) final
          contenders be determined.
          <br /> <br />
          The names and recipes of the finalists will be posted on
          Topperscontest.ca for voting by the public. The voting period will run
          from June 26, 2023 – August 31, 2023 (the “
          <strong>Voting Period</strong>”). After this time, the winner will be
          determined by the greatest number of votes. In the case where there is
          a tie, Topper’s reserves the right to extend the Voting Period, eblast
          their database of Topper’s followers or generate a social post on
          Topper’s social channels where the top-two contenders are to be chosen
          between.
        </p>
        <br />
        <p>
          <strong>6. DECLARATION OF WINNERS AND AWARDING OF PRIZES:</strong> To
          be declared a winner of a Prize (the “Winner”), the selected Entrant
          must receive the greatest number of public votes during the Voting
          Period. The selected Entrant will also be required to sign a
          Declaration and Release Form (the “<strong>Release Form</strong>”), in
          which, among other things, the selected Entrant: (i) confirms
          compliance with the Official Rules; (ii) acknowledges acceptance of
          the Prize as awarded, without substitution; (iii) releases Topper’s
          (see rule 7) from any liability in connection with the Prize or any
          portion thereof or this Contest or otherwise; and (iv) agrees to the
          use of his/her name, address (city and province/territory),
          photograph, and recipe submission story without further remuneration,
          in connection with any publicity carried out by or on behalf of
          Topper’s, with respect to the Contest. The Release Form must be
          returned within the time period specified on the Release Form or the
          Prize will be forfeited. The “free pizza for a year” prize portion
          will be emailed or shipped by courier to the Winner’s address as
          provided on the Release Form within four (4) weeks of being confirmed
          a Winner.
        </p>
        <br />
        <p>
          <strong>7. GENERAL:</strong> By entering the Contest, each Entrant:
          (i) agrees to abide by these Official Rules and the decisions of
          Topper’s with respect to all aspects of the Contest, which are final;
          (ii) grants to Topper’s, in perpetuity, a non-exclusive license to
          publish, display, reproduce, modify, edit or otherwise use his/her
          Entry, in whole or in part, for advertising or promoting the Contest
          or for any other reason; (iii) waives all moral rights in and to
          his/her Entry in favour of Topper’s; (iv) agrees to release and hold
          harmless Topper’s and each of their respective agents, employees,
          directors, successors, and assigns (collectively, the “
          <strong>Released Parties</strong>”) from and against any and all
          claims based on publicity rights, defamation, invasion of privacy,
          copyright infringement, trade-mark infringement or any other
          intellectual property related cause of action and (v) releases
          Topper’s from any and all liability in connection with this Contest
          and his/her participation in this Contest to the full extent permitted
          by law.
          <br />
          <br />
          All Entries become the permanent property of Topper’s upon receipt and
          none will be returned. No correspondence will be entered into except
          with the selected Entrants. The Contest is subject to all applicable
          federal, provincial and municipal laws.
          <br />
          <br />
          Topper’s accepts no responsibility for loss, damage or claims caused
          by or resulting from the Contest or a Prize or for any other reason.
          By entering and/or accepting a Prize, each Entrant consents to the use
          of his/her name, address (city), photograph and recipe submission
          story, without further notice or remuneration, in connection with any
          publicity carried out by or on behalf of Topper’s with respect to the
          Contest.
          <br />
          <br />
          Topper’s will not be responsible for late, lost, illegible,
          incomplete, falsified or destroyed entries and all such entries are
          void. Entries that have been falsified, tampered with or altered are
          void. Topper’s will not be liable for any failure of the Contest
          Website or any Social Media Entry Form, does not assume any
          responsibility for incorrect or inaccurate capture of Entry
          information, technical malfunctions, human or technical error,
          printing errors, lost, delayed or garbled data or transmissions,
          omission, interruption, deletion, defect or failures of any telephone
          or computer lines or networks, computer equipment, software or any
          combination thereof. The use of an invalid email address will
          disqualify the Entry. Users spamming the same email address will
          disqualify the Entry. In the event of a dispute, a selected Entrant
          may be required to provide proof that he/she is the authorized account
          holder of the email address associated with the selected
          Entry. “Authorized account holder” is defined as the person who is
          assigned an email address by an internet provider, online service
          provider, or other organization (e.g. business, educational institute,
          etc.) that is responsible for assigning email addresses for the domain
          associated with the submitted email address.  The sole determinant of
          the time for the purposes of a valid Entry in this Contest will be the
          Contest server machine(s). In the event it is determined that an
          Entrant has entered in a fashion not sanctioned by these Official
          Rules and/or has submitted more than the number of Entries permitted
          by these Official Rules, only the first Entry submitted by the Entrant
          will be eligible. All subsequent Entries submitted by the Entrant will
          be disqualified.
          <br />
          <br />
          Topper’s reserves the right to terminate or suspend this Contest or to
          amend the Official Rules at any time and in any way, without prior
          notice. Without limiting the foregoing, if, for any reason, the
          Contest is not capable of running as originally planned, Topper’s
          reserves the right to cancel the Contest and conduct a draw from all
          previously received eligible Entries. Topper’s shall not be held
          responsible for any problems, errors or negligence that may arise or
          occur in connection with the Contest.
          <br />
          <br />
          All intellectual property associated with the Contest, including but
          not limited to trademarks, trade names, logos, designs, promotional
          materials, web pages, source code, drawings, illustrations, slogans
          and representations is owned by Topper’s and/or their affiliates. All
          rights are reserved. Unauthorized copying or use of any copyrighted
          material or intellectual property without the express written consent
          of its owner is strictly prohibited.
          <br />
          <br />
          In the event of any discrepancy or inconsistency between these
          Official Rules and disclosures or other statements contained in any
          materials related to this Contest, including, but not limited to point
          of sale, print or online advertising, these Official Rules shall
          prevail, govern and control to the fullest extent permitted by law.
        </p>
      </div>
    </section>
  );
}
